### ISSUE TITLE
Delegate Validating

### ISSUE THREAD

**Issue by st-wong** [proximax-storage/xpx-chain-web-wallet#255]
Wallet currently does not allow an account to start [delegated validating](https://bcdocs.xpxsirius.io/docs/protocol/validating/#delegated-validating), this will be a useful feature to add and it can be expanded to help with [remote delegated validating](https://github.com/proximax-storage/xpx-chain-web-wallet/issues/256) when the core is ready.

**Comment by Sateetje** [comment]
CLI tool: https://github.com/proximax-storage/xpx-mainnet-chain-onboarding/tree/master/docker-method/tools

**Comment by otsybizov** [comment]
The task to track integration of this feature from symbol:
https://app.clickup.com/t/88v7yf
